basePath: /api/v1
definitions:
  main.Item:
    properties:
      text:
        type: string
    type: object
  main.Response:
    properties:
      int64:
        type: integer
      string:
        type: string
      world:
        $ref: '#/definitions/main.Item'
    type: object
host: localhost:1314
info:
  contact: {}
  description: This is a sample swagger server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      operationId: HelloWorldIndex
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Hello World !
      tags:
      - HelloWorld
swagger: "2.0"
